{
 "title": "Tool State - Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Erro Threshold Inferior",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_state{type=\"ErroThresholdInferior\"}"
    }
   ]
  },
  {
   "title": "Contagem de requisições POST para /tool-state",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/tool-state\", method=\"POST\"}"
    }
   ]
  },
  {
   "title": "Estado da Aplicação ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "app_state", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Erro Threshold Superior",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_state{type=\"ErroThresholdSuperior\"}"
    }
   ]
  },
  {
   "title": "Aplicação Estável",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_state{type=\"Estavel\"}"
    }
   ]
  },
  {
   "title": "Medidas atuais por tipo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "app_measure", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Histórico das medidas por tipo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "app_measure", "legendFormat": "{{type}}" }
   ]
  }
 ]
}